One of the constructor was missing a RMM_EXEC_CHECK_DISABLE annotation, resulting in (false positive ?) warnings:
error: calling a __host__ function("rmm::device_buffer::operator =(rmm::device_buffer&&)") from a __host__ __device__ function("rmm::device_uvector<unsigned long> ::operator =") is not allowed